#[allow(dead_code)]
pub const STAR_TREK: [&str; 69] = [
  "James T. Kirk",
  "Mr. Spock",
  "Leonard McCoy",
  "Lieutenant Uhura",
  "Chief Engineer Montgomery Scott",
  "Helmsman Hikaru Sulu",
  "Security Chief Pavel Chekov",
  "Captain Jean-Luc Picard",
  "Commander William Riker",
  "Lieutenant Data",
  "Geordi LaForge",
  "Counselor Deanna Troi",
  "Worf",
  "Dr. Beverly Crusher",
  "Neelix",
  "Kes",
  "Chakotay",
  "Tuvok",
  "Kathryn Janeway",
  "Tom Paris",
  "B'Elanna Torres",
  "Seven of Nine",
  "The Doctor",
  "Jonathan Archer",
  "T'Pol",
  "Malcolm Reed",
  "Hoshi Sato",
  "Travis Mayweather",
  "Gabriel Lorca",
  "Michael Burnham",
  "Saru",
  "Sylvia Tilly",
  "Paul Stamets",
  "Ash Tyler",
  "Christopher Pike",
  "Philippa Georgiou",
  "Spock (Discovery)",
  "Amanda Grayson",
  "Sarek",
  "Harry Mudd",
  "Q",
  "Khan Noonien Singh",
  "Klingon Captain Worf",
  "Klingon Chancellor Gorkon",
  "Klingon General Martok",
  "Romulan Commander Sela",
  "Borg Queen",
  "Benjamin Sisko",
  "Jadzia Dax",
  "Odo",
  "Kira Nerys",
  "Garrity",
  "Jake Sisko",
  "Ezri Dax",
  "Quark",
  "Worf (DS9)",
  "Neelix (DS9)",
  "Dr. Bashir",
  "Nog",
  "Voyager crew",
  "Discovery crew",
  "Picard crew",
  "Strange New Worlds crew",
  "Elim Garak",
  "Guinan",
  "Lwaxana Troi",
  "Alexander Rozhenko",
  "Wesley Crusher",
  "Reg Barclay",
];
