#[allow(dead_code)]
pub const DIABLO_II: [&str; 26] = [
    "Akara",
    "Decard Cain",
    "Charsi",
    "Gheed",
    "Griswold",
    "Drognan",
    "Fara",
    "Lysander",
    "Elzix",
    "Ormus",
    "Hratli",
    "Asheara",
    "Alkor",
    "Jamella",
    "Halbu",
    "Malah",
    "Kashya",
    "Larzuk",
    "Anya",
    "Nihlathak",
    "Qual-Kehk",
    "Radament",
    "Shenk the Overseer",
    "Tal Rasha",
    "Warriv",
    "Tyrael",
];

#[allow(dead_code)]
pub const WARCRAFT_3: [&str; 31] = [
    "Garrosh Hellscream",
    "Cairne Bloodhoof",
    "Vol'jin",
    "Sylvanas Windrunner",
    "Warchief Thrall",
    "Jaina Proudmoore",
    "Tyrande Whisperwind",
    "Genn Greymane",
    "Anduin Wrynn",
    "Arthas Menethil",
    "Illidan Stormrage",
    "Maiev Shadowsong",
    "Kael'thas Sunstrider",
    "Malfurion Stormrage",
    "Muradin Bronzebeard",
    "Rexxar",
    "Uther the Lightbringer",
    "Kel'Thuzad",
    "Kil'jaeden",
    "Thrall",
    "Kael'thas Sunstrider",
    "Vashj",
    "Anub'arak",
    "Chen Stormstout",
    "Garithos",
    "Magtheridon",
    "Medivh",
    "Nazgrel",
    "Prophet Velen",
    "Teron Gorefiend",
    "Tichondrius",
];
